LineLength:
  Description: 'Limit lines to 130 characters.'
  Max: 130

StringLiterals:
  EnforcedStyle: single_quotes

HashSyntax:
  Description: >
                 Prefer Ruby 1.9 hash syntax { a: 1, b: 2 } over 1.8 syntax
                 { :a => 1, :b => 2 }.
  EnforcedStyle: ruby19
  Enabled: true

RedundantBegin:
  Enabled: false
