app:
  volumes:
    - ./:/var/www/bunny/
  build: ./
  environment:
    DATABASE_HOST: db
    DATABASE_USERNAME: root
    DATABASE_PASSWORD: super-secret
    PORT: 3000
  links:
    - db
  ports:
    - '3000:3000'
  command: foreman start
db:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: super-secret
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  volumes:
    - ./.mysql:/var/lib/mysql
  restart: always
